apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: spc-tls
  namespace: istio-system
spec:
  commonName: "spring-petclinic.pa-bthelen-demo-1.betlab.cloud"
  dnsNames:
    - "spring-petclinic.pa-bthelen-demo-1.betlab.cloud"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: spc-tls
